[package]
name = "drv-sidecar-seq-api"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-idol-err = {path = "../../lib/derive-idol-err" }
userlib = {path = "../../sys/userlib"}
num-traits = { version = "0.2.12", default-features = false }
zerocopy = "0.6.1"
drv-fpga-api = {path = "../fpga-api"}
drv-sidecar-mainboard-controller-api = {path = "../sidecar-mainboard-controller-api"}

[build-dependencies]
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}
